//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo.Models
{
	using System;
	using System.Collections.Generic;
	using Newtonsoft.Json;
	public partial class OrderLine
	{
		public int OrderId { get; set; }
		public int LineNumber { get; set; }
		public int ProductId { get; set; }
		public decimal Qty { get; set; }
		public decimal LineTotal { get; set; }

		[JsonIgnore]
		public virtual Order Order { get; set; }
		[JsonIgnore]
		public virtual Product Product { get; set; }
	}
}
